### ISSUE TITLE
Upgrade from Reviews 2.4 fails

### ISSUE THREAD

**Issue by rmaiwald** [zikula-modules/Reviews#35]
I tested Reviews 2.5.0 with Zikula 1.3.9 to upgrade from Zikula 1.2.10. Upgrading from Reviews 2.4 fails with error message "An error was encountered while dropping the tables for the Reviews extension.".

The Installer function upgrade() correctly renames the database table reviews (upgrade 2.4 to 2.4.1). But the following DoctrineHelper::updateSchema() fails (see also zikula-modules/Weblinks issue #36). I am not familiar enough with the Zikula object modell to find the reasons.

Can anyone help me solve this problem?

Thanks in advance
Reiner

**Comment by Portugao** [comment]
I will see.

**Comment by Portugao** [comment]
Is there an old module installed with a longblob field?
Which php version?

**Comment by Portugao** [comment]
Did you try to upgrade to 2.4.1 and then to 2.5.0?

**Comment by rmaiwald** [comment]
I use PHP 5.5.15 (XAMPP 1.8.3). And I have searched for tables with blob columns and found one: mediashare_mediadb.

After deleting this table the upgrade from Reviews 2.4 to 2.5.0 was fine, exept the last step. Deleting the table reviews results in the error message "reviews does not point to a valid table definition" (DBUtil::droptable(), line 3670). I dropped it manually.

**Comment by Portugao** [comment]
So i close this.
Feel free to reopen.
