### ISSUE TITLE
Upgrade Reviews from 2.4.1 in ZK 1.4

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/Reviews#38]
Hello.

I am using ZK 1.4.0 (upgrade from ZK 1.3) with Reviews 2.4.1 version. I have download the release 2.5 of Reviews, but when i upgrade the module, i have the error:
An error was encountered while dropping the tables for the Reviews extension.
Extension upgrade failed!

The schema is not upgraded

**Comment by Portugao** [comment]
Reviews 2.5.0 is not for Zik 1.4.0. Mittwoch, 26 August 2015, 02:34nachm. +0200 von KratorD < notifications@github.com> :

**Comment by KratorD** [comment]
Yes, I know, but ZK 1.4 is compatible with 1.3 modules and Reviews 2.5.0 is a 1.3 module, is true?
So, I was thinking that Reviews will work in ZK 1.4.

Thanks @Portugao

**Comment by Portugao** [comment]
Sorry. Reviews is built with MOST. So 2.5.0 does not work among ZIK 1.4.x.

**Comment by Portugao** [comment]
The core_max var is set to 1.3.99.
So i close this issue.

**Comment by KratorD** [comment]
Thanks you @Portugao 
Will there be a version of Reviews for ZK 1.4 when MOST is upgrade?

**Comment by Portugao** [comment]
See #39 !
I cannot say at this moment, when I do this. It depends on the development of the core.
